# Generated by Django 5.1.1 on 2024-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IridescentCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField()),
                ('current_iridescent', models.IntegerField()),
                ('currrent_xp', models.IntegerField()),
                ('iridescent_needed', models.IntegerField()),
                ('xpon', models.BooleanField()),
            ],
        ),
    ]
